version: "3.9"

services:
    nginx:
        image: nginx:latest
        ports:
            - "81:80"
        restart: unless-stopped
        volumes:
            - './:/var/www/'
            - '.docker/nginx/conf.d:/etc/nginx/conf.d/'
        depends_on:
            - php

    php:
        build:
            context: .docker/php
            dockerfile: dockerfile
        restart: unless-stopped
        volumes:
            - '.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini'
            - './:/var/www/'
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - "5433:5432"
        environment:
            POSTGRES_HOST: "${DB_HOST}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            PGDATA: "/var/lib/postgresql/data"
        volumes:
            - 'pgdata:/var/lib/postgresql/data/'
volumes:
    pgdata:
